### ISSUE TITLE
photos from google do not open in lightbox

### ISSUE THREAD

**Issue by alealvisi** [van4two/van4two.github.io#19]

**Comment by cooked** [comment]
lightbox is fixed  now for both local and google photos.... still pending few cosmetic updates:
- remove white border around pic
- space caption apart from pic and photo index

**Comment by cooked** [comment]
styled 

<img width="1114" alt="image" src="https://user-images.githubusercontent.com/1381353/199858427-53ab874e-2165-4f20-bb62-f57441ee1f90.png">
