### ISSUE TITLE
posts shall be organized in subfolders

### ISSUE THREAD

**Issue by alealvisi** [van4two/van4two.github.io#2]

**Comment by cooked** [comment]
see here for reference https://stackoverflow.com/questions/15279147/how-does-jekyll-treat-posts-in-posts-subdir

**Comment by cooked** [comment]
that is already supported... just create any subfolder of the folder _posts (grouping for example by country like _posts/norway)
and every post inside them is picked up normally

note that the address of the post won't change, will only be the same <year>/<month>/<day>/name-of-the-post as before

same thing for linking to a post in a page, use the usual name like
{% post_url <year>/<month>/<day>/name-of-the-post as before %}
