### ISSUE TITLE
next and previous links missing

### ISSUE THREAD

**Issue by alealvisi** [van4two/van4two.github.io#24]

**Comment by cooked** [comment]
functionality implemented
TODO: proper styling of the next/prev buttons

**Comment by cooked** [comment]
<img width="1109" alt="image" src="https://user-images.githubusercontent.com/1381353/199851803-ce3b80b8-25fd-4973-b264-e609d98d01bb.png">

<img width="1118" alt="image" src="https://user-images.githubusercontent.com/1381353/199851883-a52732f0-6e15-45d9-81a2-3955aea1c529.png">
