### ISSUE TITLE
find shortcut for mark down link

### ISSUE THREAD

**Issue by alealvisi** [van4two/van4two.github.io#3]

**Comment by cooked** [comment]
turns out someone was sick as well of having to write all those target=_blank 
https://keith-mifsud.me/projects/jekyll-target-blank

**Comment by cooked** [comment]
it seems that it only works correctly when placed inside the plugin group

![image](https://user-images.githubusercontent.com/1381353/185653417-7b4e7431-a1b7-487c-9954-d13b40881daf.png)
