### ISSUE TITLE
Photos from Gphotos and from the site folder have open in a different way

### ISSUE THREAD

**Issue by alealvisi** [van4two/van4two.github.io#38]
If u try to open a photo taken from Google Photos gallery and one other the is conserved in the site folder, the open in two differen way, try for example Verso l'Oppland https://van4two.github.io/2019/07/01/norway_02-oppland.html where the 1° pic is from Gphotos and the 2° from the folder

**Comment by cooked** [comment]
see also: 
In the online site, the photos dimensions change, apparently without any rule (maybe the difference is beewtween the photos taken from Gphoto gallery and the photos which are in the site folder (for example, check Fiordi Est 2)

**Comment by cooked** [comment]
it was my error... all along... I was trying to change the size of the linked image in the lightbox but not the its placeholder in the page

![image](https://user-images.githubusercontent.com/1381353/200096477-b8210b7b-7d50-47b6-a345-967f271a3b16.png)
