### ISSUE TITLE
map tiles shall migrate to stadia

### ISSUE THREAD

**Issue by alealvisi** [van4two/van4two.github.io#72]
Stamen maps current provider will not be active anymore starting 31/10
tiles are now hosted at [stadia](https://stadiamaps.com/)

**Comment by cooked** [comment]
https://docs.stadiamaps.com/guides/migrating-from-stamen-map-tiles/

changes:
- created an account on stadia, auth the domain van42.com
- changed tiles address in the code to
 L.tileLayer('https://tiles.stadiamaps.com/tiles/stamen_toner_lite/{z}/{x}/{y}{r}.png')
